global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'academic-system'

scrape_configs:
  - job_name: 'spring-boot-app'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']